version: '3.8' # Or a suitable version for your setup

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo

  app:
    build:
      context: .
    container_name: todo-backend
    depends_on:
      - db
    ports:
      - "8087:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

